POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Rick72",
    "number": "123-1234-123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "rIcK72",
    "number": "123-1234-123"
}


###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Morty23",
    "number": "123-1234-123"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Morty"
     
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "1234567890"
    
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{

}

